name: Save Docker Image With Name

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Nombre de la imagen Docker (e.g. ubuntu:22.04)'
        required: true
        default: 'ubuntu:22.04'

jobs:
  save-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar imagen solicitada
        run: echo "Descargando imagen ${{ github.event.inputs.image_name }}"

      - name: Descargar imagen Docker
        run: docker pull ${{ github.event.inputs.image_name }}

      - name: Crear nombre de archivo seguro
        id: filename
        run: |
          # Reemplazar caracteres no seguros por guiones
          SAFE_NAME=${{ github.event.inputs.image_name }} | sed 's/[:\/]/_/g'
          echo "imagen_segura=$SAFE_NAME" >> $GITHUB_OUTPUT

      - name: Guardar imagen Docker en archivo
        run: |
          # Utilizar el nombre seguro y agregar extensión de gzip
          FILE_NAME="${{ steps.filename.outputs.imagen_segura }}.tar.gz"
          docker save ${{ github.event.inputs.image_name }} | gzip > "$FILE_NAME"

      - name: Subir imagen como artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ${{ steps.filename.outputs.imagen_segura }}.tar.gz
